const { execSync } = require('child_process');
const fs = require('fs');

const { lesson, date } = JSON.parse(fs.readFileSync('temp-lesson-data.json', 'utf8'));

// Configure git
execSync('git config user.name "System Design Bot"');
execSync('git config user.email "action@github.com"');

// Create and switch to new branch
const branchName = `lesson-${date}`;
execSync(`git checkout -b ${branchName}`);

// Add files
execSync('git add lessons/ docs/');
execSync(`git commit -m "Day ${lesson.day}: ${lesson.title}

📚 Today's Topic: ${lesson.topic}
🎯 Key Focus: ${lesson.key_concepts.join(', ')}

[Quiz Available](../docs/quiz-${date}.html)"`);

execSync(`git push origin ${branchName}`);

// Create PR using GitHub CLI (if available) or API
const prTitle = `📖 Day ${lesson.day}: ${lesson.title}`;
const prBody = `## Today's System Design Topic: ${lesson.topic}

${lesson.summary}

### 🎯 What you'll learn:
${lesson.key_concepts.map(concept => `- ${concept}`).join('\n')}

### 🌟 Real-world context:
${lesson.real_world_example}

### 💭 Discussion starters:
${lesson.discussion_questions.map((q, i) => `${i + 1}. ${q}`).join('\n')}

### 📝 [Take the interactive quiz](../docs/quiz-${date}.html)

---
*Auto-generated by System Design Daily Deep-Dive*`;

try {
  execSync(`gh pr create --title "${prTitle}" --body "${prBody}" --head ${branchName} --base main`);
} catch (error) {
  console.log('GitHub CLI not available, PR creation skipped');
}