name: Daily System Design Deep-Dive

on:
  schedule:
    - cron: '0 12 * * *'  # 8 AM EST daily
  workflow_dispatch:  # Manual trigger for testing

jobs:
  generate-lesson:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate today's lesson
      run: node scripts/generate-lesson.js
      
    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node scripts/create-pr.js
      
    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: node scripts/send-discord.js